# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de3f28d0cc4cb827acff318ab115bebf"
name = "dreambazaarauto"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
