# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1df5153a13054d14998f6f0ad2e7bdb5"
name = "dreambazaarauto"
application_url = "https://rules-logan-aviation-athletes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_metaobjects,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://rules-logan-aviation-athletes.trycloudflare.com/api/auth"
]
